# Count basic stats
#
# Example:
#
#   env GENE='BRCA2' QUALITY=1 ~/izip/git/opensource/ruby/bioruby-rdf/scripts/sparql.sh sparql/variants/count.rq
#   

<%
   count=ENV['COUNT']
   hc=ENV['HC']
   count = 'mutations' if !count
%>

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>

<% if count == 'quality' %>
# SELECT ?species ?source (COUNT(?id) AS ?num) WHERE
# SELECT ?sample ?quality WHERE 
SELECT ?quality (COUNT(?sample) AS ?num) WHERE 
{
  ?sid sample:identifier ?identifier ;
       sample:sample ?sample ;
       sample:cnv_rank ?cnv_rank ;
       sample:quality ?quality .
}
GROUP by ?quality
# ORDER by ?species ?source

<% else %>

# Count mutations
# SELECT ?quality (COUNT(?sample) AS ?num) WHERE 
SELECT ?identifier (COUNT(?id) as ?num) WHERE 
{
  ?id :type :somatic ;
      :caller :somaticsniper ;
      <% if hc %>
      :hc true ;
      <% end %>
      :identifier ?identifier .
}
GROUP by ?identifier
<% end %>

