# Fetch somatic variants for a number of known cancer genes
#
# Example:
#
#   ~/izip/git/opensource/ruby/bioruby-rdf/scripts/sparql.sh mutations.rq
#

<% 
   plot=ENV['PLOT']
   freq=ENV['FREQ']
%>

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>
prefix : <http://biobeat.org/rdf/freebayes>  

# SELECT ?gene_name ?chr ?pos ?sample (count(?sample) as ?num) WHERE {
<% if plot=="PLOT1" %>
SELECT DISTINCT ?gene_name ?chr ?pos ?alt ?sample WHERE {
<% else %>
SELECT DISTINCT ?chr ?pos ?ref ?alt ?sample ?freq ?gene_name ?n_ro ?n_ao ?t_ro ?t_ao WHERE {
<% end %>
  ?freebayes  seq:chr  ?chr ;
              seq:pos  ?pos ;
              seq:ref  ?ref ;
              seq:alt  ?alt ;
              db:id    db:freebayes ;
              seq:variant_type freebayes:somatic ;
              mbc:sample ?sample .
  OPTIONAL {
    ?freebayes freebayes:t_ao ?t_ao;
               freebayes:t_ro ?t_ro;
               freebayes:n_ao ?n_ao;
               freebayes:n_ro ?n_ro.
  }

  ?snv1       seq:chr  ?chr ;
              seq:pos  ?pos ;
              db:id    db:snv1 ;
              seq:gene_name  ?gene_name .
  <% if freq %>
    OPTIONAL { 
    ?population seq:chr ?chr ;
                seq:pos ?pos ;
                seq:alt ?alt ;
                db:type db:population ; 
                seq:freq ?freq 
    }.
    FILTER ( !bound(?freq) || ?freq <= <%= freq %> ) .
  <% end %>

}
# GROUP BY ?chr ?pos
# ORDER BY ?chr ?pos

