# Fetch somatic variants for a number of known cancer genes
#
# Example:
#
#   ~/izip/git/opensource/ruby/bioruby-rdf/scripts/sparql.sh mutations.rq
#

<% 
   plot=ENV['PLOT']
%>

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>
prefix : <http://biobeat.org/rdf/freebayes>  

# SELECT ?gene_name ?chr ?pos ?sample (count(?sample) as ?num) WHERE {
<% if plot=="PLOT1" %>
SELECT DISTINCT ?gene_name ?chr ?pos ?alt2 ?sample WHERE {
<% else %>
SELECT DISTINCT ?chr ?pos ?ref ?alt ?ref2 ?alt2 ?dbsnp ?sample ?af ?gene_name ?cancer ?breast_cancer ?variant_type ?vt ?descr ?cosmicid WHERE {
<% end %>
  ?freebayes  seq:chr  ?chr ;
              seq:pos  ?pos ;
              db:id    db:freebayes ;
              seq:variant_type freebayes:somatic ;
              mbc:sample ?sample .
  # OPTIONAL { ?freebayes seq:ref  ?ref2 }
  OPTIONAL { ?freebayes seq:alt  ?alt2 }
  ?snvid      seq:chr  ?chr ;
              seq:pos  ?pos ;
              db:id    db:snv1 ;
              seq:gene_name  ?gene_name ;
  # ?snpid seq:chr ?chr ;
  #        seq:pos ?pos .
  # MINUS { ?snpid  db:id   db:cosmic } .
}
# GROUP BY ?chr ?pos
# ORDER BY ?chr ?pos

