prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix hgnc: <http://identifiers.org/hgnc.symbol/>
prefix doi: <http://dx.doi.org/>
prefix bed: <http://biobeat.org/rdf/bed#> 
prefix snv1: <http://biobeat.org/rdf/annotated-snv#> 
prefix sample: <http://biobeat.org/rdf/sample#>
prefix annotate: <http://biobeat.org/rdf/annotate#> 
prefix cosmic: <http://biobeat.org/rdf/cosmic/mutation#> 
prefix hgmd: <http://biobeat.org/rdf/hgmd#> 
prefix dbsnp: <http://biobeat.org/rdf/dbsnp#> 
prefix freebayes: <http://biobeat.org/rdf/freebayes#> 
prefix db: <http://biobeat.org/rdf/db> 
prefix seq: <http://biobeat.org/rdf/seq> 
prefix annotate: <http://biobeat.org/rdf/annotate> 


