<%
   filter=ENV['FILTER']
%>

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>

SELECT ?member WHERE {
  ?id :chr ?chr .
  ?id :pos 10338145 .
  ?id :pos ?pos .
  ?id :sift ?sift .
  ?id :polyphen ?polyphen .

  # ?id :transcript_id ?transcript .
}
