<%
   filter=ENV['FILTER']
%>

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>

SELECT ?tid ?chr ?pos ?polyphen ?sift WHERE {
  ?id :chr ?chr .
  ?id :pos ?pos .
  ?tid :snv_id ?id .
  ?tid :polyphen ?polyphen .
  ?tid :sift ?sift .
  # ?id :transcript_id ?transcript .
  #?id :sift ?sift .
  #?id :polyphen ?polyphen .
}
