# Fetch varscan2 germline variants for a number of known cancer genes.
#
# Example:
#
#   ~/izip/git/opensource/ruby/bioruby-rdf/scripts/sparql.sh sparql/variants/varscan2_germline.rq
#
#   env GENE='BRCA2' FILTER="015T" ~/izip/git/opensource/ruby/bioruby-rdf/scripts/sparql.sh sparql/variants/varscan2_germline.rq
#   

<%
   filter=ENV['FILTER']
   gene=ENV['GENE']
   type=ENV['TYPE']
   hc=ENV['HC']
   cosmic=ENV['COSMIC']
   dbsnp=ENV['DBSNP']
   quality=ENV['QUALITY']
   remark=ENV['REMARK']
   type = 'somatic' if !type 
%>

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>

# SELECT DISTINCT ?sample ?cnv_rank ?gene ?chr ?pos ?var ?snp_id ?freq ?quality ?type ?remark WHERE {
SELECT DISTINCT ?sample ?gene ?chr ?pos ?ref ?call ?var ?snp_id ?cosmicid ?cancer ?freq ?remark WHERE {
  # Reduce samples
  ?sid sample:identifier ?identifier ;
       sample:sample ?sample ;
       sample:cnv_rank ?cnv_rank ;
       sample:quality ?quality .
  <% if quality %>
  FILTER ( ?quality = "high" || ?quality = "good" ) .
  <% end %>
  <% if filter %>
    FILTER( CONTAINS( ?identifier,"<%= filter %>" ) ) .
  <% end %>
  # Select variants
  ?id :chr ?chr ;
      :pos ?pos ;
      :ref ?ref ;
      :variant ?call ;
      <% if type %>
      :type :<%= type %>;
      <% end %>
      :type ?type ;
      :identifier ?identifier ;
      <% if hc %>:hc true ; <% end %>
      :caller ?caller .
  # Select on effect (is a snv1)
  <% if cosmic %>
  ?cosmic cosmic:chr ?chr ;
          cosmic:pos ?pos ;
          cosmic:cosmic ?cosmicid ;
          cosmic:cancer ?cancer ;
          cosmic:descr ?remark ;
          cosmic:aa_mutation ?aa ;
          cosmic:nuc_mutation ?var ;
          cosmic:gene_name ?gene .
  <% elsif dbsnp %>
  ?snp dbsnp:chr ?chr ;
       dbsnp:pos ?pos ; 
       dbsnp:gene_name ?gene ;
       dbsnp:snpid ?snp_id .
       # dbsnp:type ?type 
  OPTIONAL { ?snp dbsnp:descr ?remark }.
  <% else %>
  ?ann snv1:chr ?chr ;
       snv1:snv true ;
       snv1:pos ?pos ;
       snv1:var ?var ;
       # snv1:aa_var ?aa ;
       snv1:effect ?effect ;
       snv1:snp_id ?snp_id ;
       snv1:gene_name ?gene .
  <% end %>
  # Now filter genes
  <% if gene %>
    FILTER( ?gene = "<%= gene %>" ) .
  <% else %>
    # ?anng annotate:gene ?gene ;
    #       annotate:tumor_suppressor true .
    # BRCA1 BRCA2 ATM CHEK2 TP53 APC FAS RB1 PLCG1
    # FILTER( ?gene="BRCA1"||?gene="BRCA2"||?gene="ATM"||?gene="CHECK2"||?gene="TP53"||?gene="APC"||?gene="FAS"||?gene="RB1"||?gene="PLCG1" ) .
    FILTER ( CONTAINS("BRCA1",?gene) ) .
  <% end %>
  <% if type=='germline' %>
  OPTIONAL { ?id :variant_frequency_normal ?freq }
  <% else %>
  OPTIONAL { ?id :variant_frequency_tumor ?freq }
  <% end %>
  <% if remark %>
  OPTIONAL { ?ann snv1:remark ?remark }
  <% end %>
}
