# Fetch varscan2 germline variants for a number of known cancer genes.
#
# Example:
#
#   ~/izip/git/opensource/ruby/bioruby-rdf/scripts/sparql.sh sparql/variants/varscan2_germline.rq
#
#   env GENE='BRCA2' FILTER="015T" ~/izip/git/opensource/ruby/bioruby-rdf/scripts/sparql.sh sparql/variants/varscan2_germline.rq
#   

<%
   filter=ENV['FILTER']
   gene=ENV['GENE']
   type=ENV['TYPE']
   hc=ENV['HC']
   quality=ENV['QUALITY']
   type = 'somatic' if !type 
%>

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>

SELECT DISTINCT ?sample ?cnv_rank ?gene ?chr ?pos ?var ?snp_id ?freq ?quality ?remark WHERE {
  # Reduce samples
  ?sid sample:identifier ?identifier ;
       sample:sample ?sample ;
       sample:cnv_rank ?cnv_rank ;
       sample:quality ?quality .
  <% if quality %>
  FILTER ( ?quality = "high" || ?quality = "good" ) .
  <% end %>
  <% if filter %>
    FILTER( CONTAINS( ?identifier,"<%= filter %>" ) ) .
  <% end %>
  # Select variants
  ?id :chr ?chr ;
      :pos ?pos ;
      :variant ?var ;
      :type :<%= type %>;
      :identifier ?identifier ;
      <% if hc %>:hc true ; <% end %>
      :caller ?caller .
  # Select on effect (is a snv1)
  ?ann snv1:chr ?chr ;
       snv1:snv true ;
       snv1:pos ?pos ;
       snv1:effect ?effect ;
       snv1:snp_id ?snp_id ;
       snv1:gene_name ?gene .
  # Now filter genes
  <% if gene %>
    FILTER( ?gene = "<%= gene %>" ) .
  <% else %>
    ?anng annotate:gene ?gene ;
          annotate:tumor_suppressor true .
    # BRCA1 BRCA2 ATM CHEK2 TP53 APC FAS RB1 PLCG1
    # FILTER( ?gene="BRCA1"||?gene="BRCA2"||?gene="ATM"||?gene="CHECK2"||?gene="TP53"||?gene="APC"||?gene="FAS"||?gene="RB1"||?gene="PLCG1" ) .
  <% end %>
  <% if type=='germline' %>
  OPTIONAL { ?id :variant_frequency_normal ?freq }
  <% else %>
  OPTIONAL { ?id :variant_frequency_tumor ?freq }
  <% end %>
  OPTIONAL { ?ann snv1:remark ?remark }
}
