#! /bin/bash
# 
# wrapper to the checked out git repository

unset a
for arg; do
  # printf -v 'a[i++]' %q "$arg"
  # printf -v temp %q "$arg"
  temp=$arg
  a+=("$temp")
done

# cmd='=====> /hpc/local/CentOS6/cog_bioinf/CuppenResearch/bioruby-table/bin/bio-table \"${a[@]}\"'
# echo "$cmd" 1>&2; 

exec /hpc/local/CentOS6/cog_bioinf/bin/ruby /hpc/local/CentOS6/cog_bioinf/CuppenResearch/bioruby-table/bin/bio-table "${a[@]}"

