#! /bin/bash
# 
# wrapper to the checked out git repository

echo "Problem with /dev/shm"
exit 1

unset a
for arg; do
  temp=$arg
  a+=("$temp")
done

exec /hpc/local/CentOS6/cog_bioinf/CuppenResearch/bio-locus/bin/bio-locus "${a[@]}"
