# Find out which samples share genes in the same gene set
#
# env FILTER=REACTOME_DOUBLE_STRAND_BREAK_REPAIR ~/izip/git/opensource/ruby/bioruby-rdf/scripts/sparql.sh gsea_samples.rq
#
<%
   filter=ENV['FILTER']
   hc=ENV['HC']
   dbsnp=ENV['DBSNP']
   cosmic=ENV['COSMIC']
%>

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>

SELECT DISTINCT ?sample ?cnv_rank ?geneset WHERE {
  ?setid gsea:geneset true ;
         rdf:label ?geneset ;
         rdf:label "<%= filter %>" ;
         gsea:gene ?gene .
  # Select variants
  ?id :chr ?chr ;
      :pos ?pos ;
      :identifier ?identifier ;
      <% if hc %>
      :hc true ; 
      <% end %>
      :type :somatic ;
      # :type :germline ;
      :caller ?caller .
  <% if dbsnp %>
  ?snp dbsnp:chr ?chr ;
       dbsnp:pos ?pos ; 
       dbsnp:gene_name ?gene .
  <% elsif cosmic %>
  ?cosmic cosmic:chr ?chr ;
          cosmic:pos ?pos ;
          cosmic:cancer ?cancer ;
          cosmic:gene_name ?gene .
  <% else %>
  ?ann snv1:chr ?chr ;
       snv1:snv true ;
       snv1:pos ?pos ;
       snv1:effect ?effect ;
       snv1:snp_id ?snp_id ;
       snv1:gene_name ?gene .
  <% end %>
  ?sid sample:identifier ?identifier ;
       sample:cnv_rank ?cnv_rank ;
       sample:sample ?sample .
  MINUS { ?sid sample:quality "low" } .
  MINUS { ?sid sample:quality "maybe" } .
}
