# Fetch HGMD germline variants for a number of known cancer genes
#
# Example:
#
#   ~/izip/git/opensource/ruby/bioruby-rdf/scripts/sparql.sh germline.rq
#
#
# <% list=1 ; list=ENV['LIST'] ; filter = true if ENV['FILTER'] ; list = list.to_i %>

<%= File.read(File.dirname(__FILE__)+'/../preamble.rq')  %>

# SELECT ?gene_name ?chr ?pos (count(?sample) as ?num) WHERE {
SELECT DISTINCT ?chr ?pos ?alt ?freq ?sample WHERE {
  ?freebayes  seq:chr  ?chr ;
              seq:pos  ?pos ;
              seq:alt  ?alt ;
              db:id    db:freebayes ;
              mbc:sample ?sample .
  OPTIONAL {
  ?population seq:chr ?chr ;
              seq:pos ?pos ;
              seq:alt ?alt ;
              db:type db:population ;
              seq:freq ?freq
  }.
  FILTER ( !bound(?freq) || ?freq <= 0.05 ) .
}
# GROUP BY ?chr ?pos
# ORDER BY ?chr ?pos

