# Fetch germline variants for a number of known cancer genes. If 
# the population freq is higher than 5% the variant is skipped.
#
# Example:
#
#   ~/izip/git/opensource/ruby/bioruby-rdf/scripts/sparql.sh germline.rq
#

<%= File.read(File.dirname(__FILE__)+'/../preamble.rq')  %>

# SELECT ?gene_name ?chr ?pos (count(?sample) as ?num) WHERE {
SELECT DISTINCT ?chr ?pos ?alt ?sample ?freq WHERE {
  ?freebayes  seq:chr  ?chr ;
              # seq:pos  100629569 ;
              seq:pos  ?pos ;
              seq:alt  ?alt ;
              seq:variant_type freebayes:germline ;
              db:id    db:freebayes ;
              mbc:sample "MBC085" ;
              mbc:sample ?sample .
  OPTIONAL {
  ?population seq:chr ?chr ;
              seq:pos ?pos ;
              seq:alt ?alt ;
              db:type db:population ;
              seq:freq ?freq
  }.
  FILTER ( !bound(?freq) || ?freq <= 0.05 ) .
}
# GROUP BY ?chr ?pos
# ORDER BY ?chr ?pos

