# Fetch HGMD germline variants for a number of known cancer genes
#
# Example:
#
#   ~/izip/git/opensource/ruby/bioruby-rdf/scripts/sparql.sh hgmd.rq
#
# lists:
#
#   1. BC and causal
#   2. Cancer and causal
#   3. SV and causal
#   4. BC associated
#   5. Cancer associated
#
<% list=1 ; list=ENV['LIST'] ; filter = true if ENV['FILTER'] ; list = list.to_i %>

<%= File.read(File.dirname(__FILE__)+'/../preamble.rq')  %>

# SELECT ?gene_name ?chr ?pos (count(?sample) as ?num) WHERE {
SELECT DISTINCT ?chr ?pos ?sample WHERE {
  ?freebayes  freebayes:chr  ?chr ;
              freebayes:pos  ?pos ;
              freebayes:sample ?sample .
}
# GROUP BY ?chr ?pos
# ORDER BY ?chr ?pos

